# Generated by Django 5.1 on 2025-03-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_data',
            new_name='EmployeeData',
        ),
    ]
